### ISSUE TITLE
CONTRIBUTING.md file missing

### ISSUE THREAD

**Issue by p1v0t** [MicrosoftDocs/visualstudio-docs.tr-tr#3]
CONTRIBUTING.md file missing in [this repo](https://github.com/MicrosoftDocs/visualstudio-docs.tr-tr) therefore some links broken on [README.md](https://github.com/MicrosoftDocs/visualstudio-docs.tr-tr/blob/live/README.md).

**Comment by LisandroSu** [comment]
Hello, @p1v0t , 
  
Thank you for your feedback. 
  
We are actively reviewing your comments and will get back to you soon. 
 
Kind regards, 
Microsoft DOCS International Team

**Comment by p1v0t** [comment]
Ohh, thank you for care.

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/visualstudio-docs #1421](https://github.com/MicrosoftDocs/visualstudio-docs/issues/1421) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @p1v0t,

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/visualstudio-docs/issues/1421

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
